name: Jekyll CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
          bundler: 2.5.23

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build --future

      - name: Test HTML (optional)
        run: |
          bundle exec htmlproofer ./_site \
            --assume-extension \
            --check-html \
            --log-level :debug \
            --disable-external

  analyse:
    name: Markdown Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Check markdown files are markdown-lint compliant
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint markdown files with markdown-lint
        uses: articulate/actions-markdownlint@v1.1.0
        with:
          # Includes some specific rules to ignore
          config: .github/workflows/markdownlint-config.json
          files: "_posts/**/*.md"
          # Ignore the built website, might have some funky files
          ignore: _site/
          # Try to fix basic errors
          fix: true