name: Deploy Site

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  set-deploy-type:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.set-output.outputs.target }}
    steps:
      - uses: actions/checkout@v4

      - name: get deployment target
        run: |
          TARGET=$(cat DEPLOY_STRATEGY)
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: check if target is valid
        if: success() && !contains(fromJSON('["gh-pages", "firebase", "none"]'), env.TARGET)
        run: echo 'Invalid Deployment Target' && exit 1

      # gh actions doesn't support using the 'env' context on job level ifs for
      # some reason smh. here we use outputs instead
      - name: set output to deploy target
        id: set-output
        run: echo "::set-output name=target::${{ env.TARGET }}"

  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Jekyll Site
        uses: sujaykundu777/jekyll-deploy-action@1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}