name: PR build / Deploy to Cloudflare Pages preview (patons02-github-io-staging.pages.dev)

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output-dir: dist
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
          bundler: 2.5.23

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./_site

  deploy:
    if: false
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./_site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_site --project-name=patons02-github-io-staging --branch=${{ github.head_ref }}